config/routes.rb
Watch::Application.routes.draw do
  get 'register', :to =>"users#new",  :as =>:register
  get 'login', :to =>"sessions#new", :as => :login
  post 'login', :to => 'sessions#create'
  get 'logout', :to => 'sessions#destroy', as:  'logout'

  get "posts/about"
  get "posts/contact"
  resources :users
  resources :posts do
	resource  :comments
  	resource :votes
end

  

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  attr_accessible :content, :post_id
  validates :content, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :url, :user_id
  has_many :comments
  has_many :votes 
  belongs_to :user
  validates :url, presence: true 
  validates :title, presence: true 
 
 #to get pretty url.
 #def to_param
 #	"#{id} #{title}".parameterize
 #end

	 def vote_count
		votes.where(direction: "up").count - votes.where(direction: "down").count
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password_digest, :username, :password, :twitter_handle
  has_secure_password
  has_many :posts, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :votes, :dependent => :destroy
end

app/models/vote.rb
class Vote <ActiveRecord::Base
	attr_accessible :direction, :post_id
	belongs_to :post
	belongs_to :user
	
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :logged_in?


  def current_user
  	#session[:user]
    session[:user_id].nil? ? nil : User.find(session[:user_id])
  end

  def logged_in?
  	 !!current_user 
  	
  end

  def require_user
  	if !logged_in?
  		 redirect_to root_path, notice: "You must be logged in for this action"

 		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_user, only: [:create]
	

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(params[:comment])
	    @comment.user = current_user

			if @comment.save 
				redirect_to post_path(@post), notice: "Comment was created  Thank you"
			else
				redirect_to post_comments_path
			end

		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :require_user, only: [:new, :create]
	def index
		@posts = Post.all		
	end

	def new
		 @post = Post.new
	end

	def about
		
	end

	
	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
		
	end

	def create
		 @post =Post.new(params[:post])
		 @post.user = current_user
		 
		 
		 	if @post.save
				redirect_to root_path
			else
				redirect_to new_post_path
			end	

	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
		user =  User.find_by_username(params[:username])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: "You are now logged in"
		else
			flash[:error] = "Could not log you in"
			render 'new'

		end
	end
		
		def destroy
			session[:user_id] = nil
			redirect_to root_path, notice: "logged out"
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
			if @user.save 
				redirect_to login_path, notice:  "Successfully registered"
			else
				render 'new', :error => " Regitration had some error"
			end
	end

		def show
			@user = User.find(params[:id])
			@posts = @user.posts
		end
	end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_filter :require_user, only: [:create]
	
	def create
		post = Post.find(params[:post_id])
		post.votes.create(direction: params[:direction])
		redirect_to root_path

		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#test to see how helpers work.
	def current_time
		Time.now
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def display_url(post)
        	if post.url.starts_with?("http://")
                return	link_to post.title, post.url
        	else
                return	link_to post.title, "http://" + post.url

        	end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
Template

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WatchLand" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Template &middot; Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
   
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">

          <% if logged_in? %>
                
                 <li><%=current_user.username.capitalize %></li>
                 
                <li> <%= link_to"Logout", logout_path %> </li>
              
            <%else%>
               
                <li>  <%= link_to"Login", login_path %></li>
                <li>   <%= link_to"Register ", register_path %></li>
            <%end%>
    
          </i>

          <li> <%=link_to "Home ",  :action=> "index" , :controller =>"posts"%>      </li>
          <li> <%=link_to "About ",  :action=> "about" , :controller =>"posts"%>     </li>
          

            
          
        </ul>
          
          
        <%=link_to (image_tag 'watch.jpg', :size => '100x100'), posts_path%>

      <hr>
      
       <%=link_to "submit a watch link", new_post_path %>
     


       
      <hr>
        <%= yield %>

      <hr>
     <div class="alert  alert-warning">
          @ 2012 watchland.com
        </div>
    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
  
  
            
           
  </body>
</html>

app/views/posts/about.html.erb
<p>Few things say more about a man than his watch. Its character, look and style can give others a peek into a man's background (and priorities) without having to ask a single question. 

<p>That is why purchasing a watch is such a personal -- and important -- decision.

<p>Of course, there are men out there who only need a watch to tell time, and for those guys a watch whose price ends with .99 would suffice. But for the rest of us, a watch has a more prominent meaning (and for the select few who dabble in the Rolex territory, it can even be an investment opportunity).

app/views/posts/contact.html.erb
<h3>CONTACT</h3>

For commissions, collaborations, advertising opportunities on the site, or just to get in touch.


<p><%=current_time %>

<%form_tag   %>

<hr>
<%=text_field_tag  "post", "Name" %></br>
<%=text_field_tag  "post", "Email" %></br>
<%=text_field_tag  "post", "Website" %></br>

 

<%=submit_tag "submit" %> 

app/views/posts/index.html.erb
<ol class="unstyled">

<%@posts.each do |post| %>


 
<li>
	<%=link_to post_votes_path(post, direction: "up"), :method => post  do %>
     <i class="icon-thumbs-up"></i>
       <% end %>
        <%=post.vote_count %>
       <%=link_to post_votes_path(post, direction: "down"),  :method => post do %>
     
       <strong><i class="icon-thumbs-down"></i>
   <%=display_url(post)%> </strong>
        <% end %>
         <h6><%= time_ago_in_words(post.created_at) %> ago by <%= post.user.username %> &nbsp
          <%=link_to "comments #{post.comments.size}",  post_path(post) %></h6> 
  
</li>


<% end %>

<ol>

app/views/posts/new.html.erb
<%=form_for @post do |f| %>
	<%if !@post.errors.any? %>
		<%@post.errors.full_messages.each do |msg| %>
		<%=msg %>
		<% end %>
<% end %>
	<%= label_tag  "Title" %>
	<%=f.text_field :title %>
	<%= label_tag  "Url" %>
	<%=f.text_field :url %></br>
	<%=f.submit "Submit" %>	
<% end %>

app/views/posts/show.html.erb
<h5><i><%=link_to @post.title, @post.url %> </h5></i> </br>

<p>
	

<h4> comments <%=@post.comments.size %></h4>
<p>
<ul>
	<%@post.comments.each do |comment| %>

		<li>
			   
			   posted by <i><%=link_to comment.post.user.username,  user_path %> </br></i>
			   <%=comment.content%> 
		</li>


 <% end %>

 </ul>

 <br/>


	

 <h4> Comment </h4>
<%=form_for [@post, @comment] do |c| %>
<%=c.text_area :content, :size => "5x2" %></br>
<%=c.submit "LEAVE  COMMENT" %>

<% end %>
	

app/views/users/new.html.erb
<h2>Please  register Here </h2>
<p>
  <% if @user.errors.any? %>
  		<%=@user.errors.full_messages %>
  	<% end %> 
<%=form_for @user do |f| %>

 <%=f.label :username %>
 <%=f.text_field :username %>
 

 <%=f.label :password %>
 <%=f.password_field :password %>

<%=f.label :twitter_handle %>
<%=f.text_field :twitter_handle %>
 <br/>
<%=f.submit "sign in" %>

<% end %>

app/views/users/show.html.erb
<h3> User Information </h3>	
<h4><%=@user.username%> </h4>
<strong>joined </strong>: <%=@user.created_at%>



<h5> Most recent posts</h5> </br>

	<%@user.posts.each  do |p| %>
			 <%=p.title %></br>		
	<% end  %>

	<h5> Most recent comments</h5> </br>
			<%@user.posts.each do |p| %>
				<%p.comments.each do |c|%>
				<%=c.content %></br>
					
		<% end %>
<% end %>
			 	
 

	